### ISSUE TITLE
NameError: name 'logger' is not defined

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#144]
If neither Y or N is pressed on *Start counterpartyd automatically on system startup? (y/n)*, this error happens.
```
Successfully installed appdirs prettytable python-dateutil flask json-rpc pytest pycoin requests Flask-HTTPAuth tornado pycrypto tendo python-bitcoinlib pytest-cov Werkzeug itsdangerous py certifi cov-core coverage
Cleaning up...
2014-11-18 09:31:01,316|DEBUG: RUNNING COMMAND: ln -sf /home/xcp/counterpartyd_build/run.py /usr/local/bin/counterpartyd
Start counterpartyd automatically on system startup? (y/n): m
Traceback (most recent call last):
  File "setup.py", line 475, in <module>
    main()
  File "setup.py", line 469, in main
    setup_startup(paths, run_as_user, with_counterblockd, with_testnet, noninteractive)
  File "setup.py", line 282, in setup_startup
    logger.error("Please enter 'y' or 'n'")
NameError: name 'logger' is not defined


```

**Comment by robby-dermody** [comment]
good find
