### ISSUE TITLE
counterparty-cli: AttributeError: 'module' object has no attribute 'SelectParams'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#175]
On Fed Node, after some hacking (see #171):

```
rippler@ubuntu:~$ sudo su -s /bin/bash -c '/home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py --config-file /home/xcp/.config/counterpartyd-testnet/counterpartyd.conf --data-dir /home/xcp/.config/counterpartyd-testnet --testnet market' xcpd
Traceback (most recent call last):
  File "/home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py", line 735, in <module>
    proxy = backend.get_proxy()
  File "/home/xcp/counterpartyd_build/dist/counterpartyd/lib/backend.py", line 19, in get_proxy
    bitcoinlib.SelectParams('testnet')
AttributeError: 'module' object has no attribute 'SelectParams'
```

What's the proper way to execute CLI commands on Fed Node? 
I ran the command directly as well, same problem.
```
rippler@ubuntu:~$ counterpartyd -V
counterpartyd v9.49.3
rippler@ubuntu:~$ python -V
Python 2.7.6
rippler@ubuntu:~$ python3 -V
Python 3.4.0
rippler@ubuntu:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

`pip3` modules:
```
appdirs (1.2.0)
apsw (3.8.2-r1)
argparse (1.3.0)
bip32utils (0.1)
bitcoin-python (0.3) # tried to uninstall, no difference
certifi (14.05.14)
chardet (2.0.1)
colorama (0.2.5)
colorlog (2.4.0)
command-not-found (0.3)
Cython (0.20.1post0)
dateutils (0.6.6)
dispatcher (1.0)
docutils (0.11)
ecdsa (0.11)
Flask (0.10.1)
Flask-HTTPAuth (2.3.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.2)
json-rpc (1.8.1)
jsonrpc (1.2)
language-selector (0.1)
MarkupSafe (0.18)
Pillow (2.3.0)
pip (1.5.4)  # on my counterpartyd Windows box it's 1.4.1
plyvel (0.9)
prettytable (0.7.2)
progressbar33 (2.4)
pycoin (0.52)
pycrypto (2.6.1)
pycurl (7.19.3)
Pygments (1.6)
pygobject (3.12.0)
pysha3 (0.3)
python-apt (0.9.3.5)
python-bitcoinlib (0.2.1)
python-dateutil (2.3)
pytz (2014.10)
pyzmq (14.0.1)
requests (2.2.1)
roman (2.0.0)
setuptools (3.3)
six (1.8.0)
Sphinx (1.2.2)
tornado (4.0.2)
ufw (0.34-rc-0ubuntu2)
urllib3 (1.7.1)
virtualenv (12.0.4)
Werkzeug (0.9.6)
```

**Comment by rippler** [comment]
With the latest (which is different from 12 hours ago) Federated Node code and manually installed missing Python dependencies (see the bottom of #171), the CLI now works so I'll close this issue and leave #171 open.

```
Successfully installed pysha3 pycrypto
Cleaning up...
rippler@ubuntu:~$ sudo su -s /bin/bash -c '/home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py --config-file /home/xcp/.config/counterpartyd-testnet/counterpartyd.conf --data-dir /home/xcp/.config/counterpartyd-testnet --testnet wallet' xcpd

TOTAL
+-------+---------+
| Asset | Balance |
+-------+---------+
+-------+---------+

rippler@ubuntu:~$ sudo pip3 list
appdirs (1.2.0)
Warning: cannot find svn location for apsw==3.8.2-r1
apsw (3.8.2-r1)
argparse (1.3.0)
certifi (14.05.14)
chardet (2.0.1)
colorama (0.2.5)
colorlog (2.4.0)
command-not-found (0.3)
dateutils (0.6.6)
dispatcher (1.0)
docutils (0.11)
Flask (0.10.1)
Flask-HTTPAuth (2.3.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.2)
json-rpc (1.8.1)
language-selector (0.1)
MarkupSafe (0.18)
Pillow (2.3.0)
pip (1.5.4)
plyvel (0.9)
prettytable (0.7.2)
progressbar33 (2.4)
pycoin (0.52)
pycrypto (2.6.1)
pycurl (7.19.3)
Pygments (1.6)
pygobject (3.12.0)
pysha3 (0.3)
python-apt (0.9.3.5)
python-bitcoinlib (0.2.1)
python-dateutil (2.3)
pytz (2014.10)
pyzmq (14.0.1)
requests (2.2.1)
roman (2.0.0)
setuptools (3.3)
six (1.5.2)
Sphinx (1.2.2)
tornado (4.0.2)
ufw (0.34-rc-0ubuntu2)
urllib3 (1.7.1)
Werkzeug (0.9.6)
```
