### ISSUE TITLE
Missing attribute 'CLIENT_VERSION' while creating binary build of counterparty v9.34.0 on Windows

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#52]
```
C:\counterpartyd_build>python -V
Python 3.3.5

C:\counterpartyd_build>counterpartyd -V

C:\counterpartyd_build>echo off
counterpartyd v9.34.0
```

Towards the end of `python setup.py build`, it throws this error:

```

Output: "C:\counterpartyd_build\dist\windows\counterpartyd_install.exe"
Install: 7 pages (448 bytes), 4 sections (4192 bytes), 845 instructions (23660 b
ytes), 247 strings (5651 bytes), 1 language table (266 bytes).
Uninstall: 3 pages (192 bytes),
1 section (1048 bytes), 385 instructions (10780 bytes), 116 strings (1819 bytes)
, 1 language table (218 bytes).
Datablock optimizer saved 9072 bytes (~0.1%).

Using zlib compression.

EXE header size:               36352 / 35840 bytes
Install code:                   5844 / 34545 bytes
Install data:                7184244 / 12946563 bytes
Uninstall code+data:            2306 / 2807 bytes
CRC (0x5674AD3B):                  4 / 4 bytes

Total size:                  7228750 / 13019759 bytes (55.5%)

1 warning:
  uninstall function "un.EnvVarUpdate" not referenced - zeroing code (179-377) o
ut

Traceback (most recent call last):
  File "setup.py", line 555, in <module>
    main()
  File "setup.py", line 536, in main
    do_build(paths, with_counterblockd)
  File "setup.py", line 466, in do_build
    installer_dest = os.path.join(paths['bin_path'], "counterpartyd-v%s-%s_insta
ll.exe" % (config.CLIENT_VERSION, arch))
AttributeError: 'module' object has no attribute 'CLIENT_VERSION'

```

**Comment by robby-dermody** [comment]
closing as binary builds no longer supported (code removed)
